[package]
name = "adnl-tcp"
version = "0.1.0"
edition = "2021"
authors = ["Andrei Kostylev <a.kostylev@pm.me>"]

[dependencies]
anyhow = { workspace = true }
rand = "0.8.5"
sha2 = "0.10.8"
hex = "0.4.3"
